#!/usr/bin/env bash
# HyperShots renderer: headless Chrome at an exact per-profile canvas.
set -euo pipefail

WS="${1:?usage: render.sh <workspace> [profile] [locale] [--grid]}"
PROFILE="${2:-iphone-6.9}"
LOCALE="${3:-en}"
GRID=0
if [ "${4:-}" = "--grid" ]; then GRID=1
elif [ -n "${4:-}" ]; then echo "ERROR: unknown arg '${4}' (only --grid is accepted)" >&2; exit 1; fi
KIT="$(cd "$(dirname "$0")/.." && pwd)"     # skills/hypershots

find_chrome() {
  if [ -n "${CHROME:-}" ]; then echo "$CHROME"; return; fi
  local mac="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
  [ -x "$mac" ] && { echo "$mac"; return; }
  for c in google-chrome chromium chromium-browser; do
    command -v "$c" >/dev/null 2>&1 && { command -v "$c"; return; }
  done
  echo "ERROR: no Chrome/Chromium found. Set \$CHROME." >&2; exit 1
}
CHROME_BIN="$(find_chrome)"

# watchdog: kill a wedged Chrome after 180s (perl ships on macOS + ubuntu CI)
guard() { perl -e 'alarm 180; exec @ARGV' -- "$@"; }

# profile -> css dims + scale. Plain assignment (not read <<< "$(...)") so an
# unknown profile trips set -e HERE, before profile.css is written.
DIMS="$(node "$KIT/scripts/lib/profile-dims.mjs" "$KIT/profiles.json" "$PROFILE")"
read -r W H SCALE OW OH <<< "$DIMS"
[ -n "$OH" ] || { echo "ERROR: bad dims line for profile $PROFILE" >&2; exit 1; }

# per-profile variable injection (the mechanism that prevents gutters).
# --grid adds --hs-grid:1: fit.js draws a labeled 50px coordinate grid overlay.
GRID_VAR=""; [ "$GRID" -eq 1 ] && GRID_VAR=" --hs-grid:1;"
cat > "$WS/profile.css" <<EOF
/* generated by render.sh — do not edit */
:root{ --panel-w:${W}px; --panel-h:${H}px;${GRID_VAR} }
EOF

SRC="$WS/panels"; [ "$LOCALE" != "en" ] && SRC="$WS/panels-$LOCALE"
# grid renders are quarantined in <locale>-grid so validate.sh never sees them
OUT="$WS/out/$PROFILE/$LOCALE"; [ "$GRID" -eq 1 ] && OUT="$WS/out/$PROFILE/$LOCALE-grid"
mkdir -p "$OUT"
# no stale outputs: a removed/renamed panel must not leave last run's files
rm -f "$OUT"/panel-*.png "$OUT"/panel-*.boxes.json

FLAGS=(--headless=new --disable-gpu --hide-scrollbars --no-sandbox
  --force-device-scale-factor="$SCALE" --window-size="$W,$H"
  --default-background-color=FFFFFFFF --force-color-profile=srgb
  --virtual-time-budget=8000)

shopt -s nullglob
PANELS=("$SRC"/panel-*.html)
[ ${#PANELS[@]} -gt 0 ] || { echo "ERROR: no panels in $SRC" >&2; exit 1; }

for f in "${PANELS[@]}"; do
  n="$(basename "$f" .html)"
  # Chrome needs an absolute file:// URL; $WS may be a relative path
  f="$(cd "$(dirname "$f")" && pwd)/$(basename "$f")"
  LOG="$OUT/$n.chrome.log"; TMP="$OUT/$n.boxes.json.tmp"
  # pass 1: screenshot (no || true — a Chrome crash/hang must fail the build)
  guard "$CHROME_BIN" "${FLAGS[@]}" --screenshot="$OUT/$n.png" "file://$f" 2>"$LOG"
  # pass 2: dump DOM -> boxes + fit failures (fit.js is deterministic across
  # passes). boxes.json is committed only on success, and a failed panel must
  # not leave its PNG behind for validate.sh to bless.
  rc=0
  guard "$CHROME_BIN" "${FLAGS[@]}" --dump-dom "file://$f" 2>>"$LOG" \
    | node -e '
      const [expW, expH] = [process.argv[1], process.argv[2]].map(Number);
      let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{
        const m=s.match(/<script[^>]*\bid="hypershots-boxes"[^>]*>(.*?)<\/script>/s);
        if(!m){console.error("ERROR: no boxes dump — is fit.js included last in the panel?");process.exit(1)}
        const j=JSON.parse(m[1]);
        if(j.panelW!==expW||j.panelH!==expH){console.error(`ERROR: panel is ${j.panelW}x${j.panelH} but profile expects ${expW}x${expH} — is profile.css linked?`);process.exit(3)}
        if(j.fitFailures.length){console.error("FIT FAILURE (copy needs a rewrite): "+j.fitFailures.join(", "));process.exit(2)}
        console.log(JSON.stringify(j,null,1));})' "$W" "$H" > "$TMP" || rc=$?
  if [ "$rc" -ne 0 ]; then
    rm -f "$OUT/$n.png" "$TMP"      # no orphan PNG, no partial boxes.json
    exit "$rc"                      # $LOG is kept for debugging
  fi
  mv "$TMP" "$OUT/$n.boxes.json"
  rm -f "$LOG"
  echo "rendered $n -> $OUT/$n.png (target ${OW}x${OH})"
done
if [ "$GRID" -eq 1 ]; then
  echo "OK: ${#PANELS[@]} panels rendered for $PROFILE/$LOCALE-grid"
  echo "*** GRID RENDER — not for upload. Debug overlay only; outputs quarantined in $OUT ***"
else
  echo "OK: ${#PANELS[@]} panels rendered for $PROFILE/$LOCALE"
fi
